spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF8
    username: root
    password: Lx5211314.
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      max-active: 20
      min-idle: 1
      max-wait: 60000
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.springboot.entity
server:
  port: 8888
  servlet:
    context-path: /demo
